
时间：2017-07-11 09:13:18,456 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：14860 

时间：2017-07-11 09:16:26,333 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：3395 

时间：2017-07-11 09:19:45,792 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11457 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Views.web._web.InitView() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Views\web\_web.cs:行号 21
   在 X.Web.Views.View.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Views\View.cs:行号 94
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31

时间：2017-07-11 09:20:15,235 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：40900 

时间：2017-07-11 09:50:32,411 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册!)","code":"用户名已被注册!"} 
时间：58734 

时间：2017-07-11 10:00:08,639 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：123 

时间：2017-07-11 10:05:14,741 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：306224 

时间：2017-07-11 10:06:10,882 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：362365 

时间：2017-07-11 10:06:45,189 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：3172 

时间：2017-07-11 10:06:51,349 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：9332 

时间：2017-07-11 10:07:06,227 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：24210 

时间：2017-07-11 10:08:14,664 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：92647 
System.ArgumentNullException: 值不能为 null。
参数名: name
   在 System.Type.GetProperty(String name)
   在 X.Web.XFace.SetParms(NameValueCollection parms) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XFace.cs:行号 55
   在 X.Web.Apis.Api.InitApi() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 23
   在 X.App.Apis.xapi.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\xapi.cs:行号 18
   在 X.App.Apis._eng.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\_eng.cs:行号 16
   在 X.Web.Apis.Api.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31

时间：2017-07-11 10:08:21,387 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：99369 
System.ArgumentNullException: 值不能为 null。
参数名: name
   在 System.Type.GetProperty(String name)
   在 X.Web.XFace.SetParms(NameValueCollection parms) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XFace.cs:行号 55
   在 X.Web.Apis.Api.InitApi() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 23
   在 X.App.Apis.xapi.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\xapi.cs:行号 18
   在 X.App.Apis._eng.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\_eng.cs:行号 16
   在 X.Web.Apis.Api.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31

时间：2017-07-11 10:08:49,047 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：127030 

时间：2017-07-11 10:08:55,373 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"接口不存在 eng.checkname","code":"0x0002"} 
时间：133355 

时间：2017-07-11 10:09:40,828 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4428 
System.ArgumentNullException: 值不能为 null。
参数名: name
   在 System.Type.GetProperty(String name)
   在 X.Web.XFace.SetParms(NameValueCollection parms) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XFace.cs:行号 55
   在 X.Web.Apis.Api.InitApi() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 23
   在 X.App.Apis.xapi.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\xapi.cs:行号 18
   在 X.App.Apis._eng.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\_eng.cs:行号 16
   在 X.Web.Apis.Api.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31

时间：2017-07-11 10:10:37,575 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：9340 
System.ArgumentNullException: 值不能为 null。
参数名: name
   在 System.Type.GetProperty(String name)
   在 X.Web.XFace.SetParms(NameValueCollection parms) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XFace.cs:行号 55
   在 X.Web.Apis.Api.InitApi() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 23
   在 X.App.Apis.xapi.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\xapi.cs:行号 18
   在 X.App.Apis._eng.InitApi() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\_eng.cs:行号 16
   在 X.Web.Apis.Api.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 28
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31

时间：2017-07-11 10:11:23,163 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：54928 

时间：2017-07-11 10:11:56,515 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：88280 

时间：2017-07-11 10:12:03,529 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：95294 

时间：2017-07-11 10:14:10,271 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：222035 

时间：2017-07-11 10:14:29,874 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：241638 

时间：2017-07-11 10:15:59,684 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：331448 

时间：2017-07-11 10:16:15,161 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：346925 

时间：2017-07-11 10:17:24,322 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：416086 

时间：2017-07-11 10:17:39,877 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：431641 

时间：2017-07-11 10:18:59,321 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：511086 

时间：2017-07-11 10:19:12,679 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：524443 

时间：2017-07-11 10:21:58,566 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：690331 

时间：2017-07-11 10:22:23,079 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(用户名已被注册)","code":"用户名已被注册"} 
时间：714843 

时间：2017-07-11 11:14:56,653 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：2771047 

时间：2017-07-11 11:16:58,451 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：7008 

时间：2017-07-11 12:09:54,048 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：175732 

时间：2017-07-11 12:10:04,645 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：186329 

时间：2017-07-11 13:36:41,205 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：82753 

时间：2017-07-11 13:36:46,182 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：87730 

时间：2017-07-11 13:36:59,041 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：100589 

时间：2017-07-11 13:37:06,378 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：107926 

时间：2017-07-11 13:38:56,667 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：218215 

时间：2017-07-11 14:24:15,073 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：101872 

时间：2017-07-11 14:24:26,562 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：113362 

时间：2017-07-11 14:24:35,503 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：122302 

时间：2017-07-11 14:26:54,826 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：11478 

时间：2017-07-11 14:29:33,404 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：170056 

时间：2017-07-11 14:35:29,116 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：525769 

时间：2017-07-11 14:35:41,839 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0022"} 
时间：538491 

时间：2017-07-11 14:42:15,088 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：931741 

时间：2017-07-11 14:46:02,071 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：1158724 

时间：2017-07-11 14:46:12,890 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：1169542 

时间：2017-07-11 15:02:21,976 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：232 
System.Data.SqlClient.SqlException (0x80131904): 已成功与服务器建立连接，但是在登录过程中发生错误。 (provider: SSL Provider, error: 0 - 远程主机强迫关闭了一个现有的连接。) ---> System.ComponentModel.Win32Exception (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.Data.x_dict.GetDictList(String code, String upval, DataClassesDataContext db) 位置 F:\HT\adle(Phone)\src\Xc\Data\DataClasses.cs:行号 71
   在 X.Web.XFace.GetDictList(String code, String upval) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XFace.cs:行号 175
   在 X.App.Apis.eng.addr.loadct.Execute() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\eng\addr\loadct.cs:行号 14
   在 X.Web.Apis.Api.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31
ClientConnectionId:db2f5de8-075b-41ce-b477-453e09d76a19
Error Number:10054,State:0,Class:20

时间：2017-07-11 15:03:09,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：47294 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.Table`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   在 System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   在 X.App.Apis.eng.login.Execute() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Apis\eng\login.cs:行号 29
   在 X.Web.Apis.Api.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Apis\Api.cs:行号 31
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

时间：2017-07-11 15:03:44,155 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：82410 

时间：2017-07-11 15:06:54,509 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：272764 

时间：2017-07-11 15:09:00,180 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：39559 

时间：2017-07-11 15:10:28,276 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：127655 

时间：2017-07-11 15:11:36,637 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：196016 

时间：2017-07-11 15:11:40,356 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：199735 

时间：2017-07-11 15:12:33,399 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"未知错误代码(密码错误)","code":"密码错误"} 
时间：252778 

时间：2017-07-11 15:34:47,311 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：50386 

时间：2017-07-11 15:44:02,460 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：605536 

时间：2017-07-11 16:46:04,850 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：4327926 

时间：2017-07-11 16:46:10,093 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：4333168 

时间：2017-07-11 16:46:22,025 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0023"} 
时间：4345101 

时间：2017-07-11 16:46:25,833 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0022"} 
时间：4348908 

时间：2017-07-11 16:46:30,413 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0022"} 
时间：4353489 

时间：2017-07-11 16:52:42,164 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：250 
System.ArgumentException: 已添加了具有相同键的项。
   在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   在 System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   在 X.App.Views.eng.goods.detail.InitDict() 位置 F:\HT\adle(Phone)\src\Web\Yfj\X.App\Views\eng\goods\detail.cs:行号 29
   在 X.Web.Views.View.GetResponse() 位置 F:\HT\adle(Phone)\src\Web\X.Web\Views\View.cs:行号 95
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 F:\HT\adle(Phone)\src\Web\X.Web\XApp.cs:行号 31

时间：2017-07-11 17:08:02,353 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(F:\HT\adle(Phone)\src\Xc\Core\Plugin\Loger.cs:46) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0004"} 
时间：864170 
